version: 1.0.{build}
image: Ubuntu
stack: jdk 8

branches:
  only:
    - master

build: off

build_script:
  - sudo apt update
  - sudo apt-get install android-sdk -y
  - export ANDROID_SDK_ROOT="/usr/lib/android-sdk/"
  - wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
  - unzip commandlinetools-linux-6609375_latest.zip
  - yes y | sudo tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT
  - sdk.dir = ~/Android/Sdk
  - sudo ./gradlew build
